Update DataManagementAnalytics-ConnectToEnvironmentsPrivately.md
Azure/data-management-zone pull request #264
Opened 2021-12-22 08:59 UTC by mariekekortsmit

Added guidance on a private jumpbox VM in case of conditional access policies on trusted devices/Intune.

## Summary of the Pull Request
Added guidance on a private jumpbox VM in case of conditional access policies on trusted devices/Intune. Recommended approach is to deploy the VM in your own subscription because of security concerns if you'd put it in a shared subscription. Putting it in your own subscription leads to some additional steps of vnet peering, route table creation, etc. All of which are described in this PR.

## References

## PR Checklist
* [x] Closes Issue #242 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA

## Validation Steps Performed

2021-12-22 15:40 UTC, marvinbuss requested changes
Great work @mariekekortsmit!
Please check my suggestions below. 👍

2021-12-22 15:40 UTC, marvinbuss commented on docs/guidance/DataManagementAnalytics-ConnectToEnvironmentsPrivately.md
> +1. Create a Vnet in your own Azure subscription, make sure that the address space does not overlap with the Vnets for the Data Management Zone `{dmz-prefix}-{environment}-vnet` or Data Landing Zone `
```suggestion
1. Create a Vnet in your own Azure subscription, make sure that the address space does not overlap with the Vnets for the Data Management Zone `{dmz-prefix}-{environment}-vnet` or Data Landing Zone(s) `{dlz-prefix}-{environment}-vnet` in the shared Azure subscription(s);
```

2021-12-22 15:40 UTC, marvinbuss commented on docs/guidance/DataManagementAnalytics-ConnectToEnvironmentsPrivately.md
> +2. Once created, go the settings pane of the new Vnet and adjust the DNS server to a Custom one with IP address 10.0.0.4 (the IP address that is associated with the Firewall in the Data Management Zo
```suggestion
2. Once created, go the settings pane of the new Vnet and adjust the DNS server to the a Custom one (in the default setup the Firewall is used as DNS Forwarder and the default IP address of the Firewall in the Data Management Zone is 10.0.0.4). Check the Vnet of the Data Landing Zone and apply the same settings to your new Vnet;
```

2021-12-22 15:40 UTC, marvinbuss commented on docs/guidance/DataManagementAnalytics-ConnectToEnvironmentsPrivately.md
> +3. Peer the Vnet to both `{dmz-prefix}-{environment}-vnet` and `{dlz-prefix}-{environment}-vnet` in your shared Azure subscription;
```suggestion
3. Peer the Vnet to both `{dmz-prefix}-{environment}-vnet` and `{dlz-prefix}-{environment}-vnet` in your shared Azure subscription(s);
```

2021-12-22 15:40 UTC, marvinbuss commented on docs/guidance/DataManagementAnalytics-ConnectToEnvironmentsPrivately.md
> +    1. In Settings > Routes add a default route to firewall with: Address prefix: 0.0.0.0/0, Next hop type: Virtual Appliance, Next hop address: 10.0.0.4 (the IP address that is associated with the F
```suggestion
    1. In Settings > Routes add a route with name `default-route-to-firewall` with: Address prefix: 0.0.0.0/0, Next hop type: Virtual Appliance, Next hop address: internal IP of your Firewall (10.0.0.4 is the default internal IP of the Azure Firewall in the Data Management Zone. Please check the Route Table in your Data Landing Zone and apply the same settings).
```

2021-12-23 08:52 UTC, mariekekortsmit reviewed
Thanks for the feedback! Adjusted it.

2021-12-23 08:58 UTC, marvinbuss approved these changes
LGTM!

2021-12-23 08:59 UTC, merged